- name: Install and run Compose
  hosts: work_instance
  become: yes
  vars_prompt:
    - name: "compose_file"
      prompt: "Enter the docker-compose file name"
      default: "docker-compose.yml"
      private: no

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Create directory for html
      file:
        path: /home/ubuntu/html
        state: directory

    - name: Stop existing Docker Compose services
      shell: cd /home/ubuntu && docker-compose down
      ignore_errors: yes

    - name: Copy selected docker-compose file
      copy:
        src: "docker-compose/{{ compose_file }}"
        dest: "/home/ubuntu/docker-compose.yml"

    - name: Run Docker Compose
      shell: cd /home/ubuntu && docker-compose -f "/home/ubuntu/docker-compose.yml" up -d
